# Generated by Django 3.2.4 on 2024-04-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Name')),
                ('search_field', models.CharField(max_length=124, verbose_name='Search Field')),
                ('intro', models.TextField(blank=True, verbose_name='Introduction')),
                ('interests', models.TextField(blank=True, verbose_name='Interests')),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='User Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
