# Generated by Django 3.2.4 on 2024-04-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='interests',
        ),
        migrations.AddField(
            model_name='member',
            name='interest1',
            field=models.TextField(blank=True, verbose_name='Interest 1'),
        ),
        migrations.AddField(
            model_name='member',
            name='interest2',
            field=models.TextField(blank=True, verbose_name='Interest 2'),
        ),
        migrations.AddField(
            model_name='member',
            name='interest3',
            field=models.TextField(blank=True, verbose_name='Interest 3'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=24, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='search_field',
            field=models.CharField(max_length=30, verbose_name='Search Field'),
        ),
    ]
