# Generated by Django 3.2.4 on 2024-03-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20240330_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category', verbose_name='Category 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts2', to='blog.category', verbose_name='Category 2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts3', to='blog.category', verbose_name='Category 3'),
        ),
    ]
